name: Deploy Production / Github

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
      - name: Install Bootstrap with npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          cd hugo
          npm install
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Write gitinfo file
        run: bin/hugo_deployment/gitversion.sh ${{ github.ref }} ${{ github.sha }} "${{ github.workflow }}"
      - name: Build Hugo Site
        run: |
          hugo  --source hugo --minify --environment production

      - name: Deploy to Production on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo/public
          publish_branch: hugo_production
          commit_message: "${{ github.ref }} ${{ github.event.head_commit.message }}"
